version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean
      - mvn package -DskipTests
  post_build:
    commands:
      - mvn test
      - echo Build completed successfully
artifacts:
  files:
    - target/spring-cloud-mutant.jar
  discard-paths: yes